authors: [SwearWord, furt]
description: Allows players to buy and sell goods on a VirtualShop.
main: org.blockface.virtualshop.VirtualShop
name: VirtualShop
version: 1.0
database: true
commands:
    buy:
        description: Buy goods for sale on the VirtualShop.
        usage: /buy <amount> <item> [maxprice]
    sell:
        description: Put goods up for sale on the VirtualShop.
        usage: /sell <amount> <item> <price> | /sell <amount> hand <price>
    cancel:
        description: Removes items from VirtualShop.
        usage: /cancel <item>
    find:
        description: Find offers for an item.
        usage: /price <item>
    stock:
        description: List items for sale.
        usage: /list [player] [page]
    sales:
        description: See sales that have been made.
        usage: /sales [player] [page]
    virtualshop:
        description: Displays help.
        usage: /virtualshop